// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

package generic

import (
	"strings"

	"github.com/cockroachdb/errors"
	"github.com/confighub/sdk/core/configkit"
	"github.com/confighub/sdk/core/configkit/yamlkit"
	"github.com/confighub/sdk/core/function/api"
	"github.com/confighub/sdk/core/function/handler"
	"github.com/confighub/sdk/core/third_party/gaby"
)

func registerSetDefaultNames(fh handler.FunctionRegistry, converter configkit.ConfigConverter, resourceProvider yamlkit.ResourceProvider) {
	fh.RegisterFunction("set-default-names", &handler.FunctionRegistration{
		FunctionSignature: api.FunctionSignature{
			FunctionName: "set-default-names",
			Parameters: []api.FunctionParameter{
				{
					ParameterName: "name",
					Required:      true,
					Description:   "Name value to set in identified name fields containing the placeholder string 'confighubplaceholder' or number 999999999",
					DataType:      api.DataTypeString,
				},
			},
			Mutating:              true,
			Validating:            false,
			Hermetic:              true,
			Idempotent:            true,
			Description:           "Set the values of identified name fields containing the placeholder string 'confighubplaceholder' or number 999999999. See https://docs.confighub.com/background/concepts/placeholders/ for more details regarding placeholder values.",
			FunctionType:          api.FunctionTypePathVisitor,
			AttributeName:         api.AttributeNameDefaultName,
			AffectedResourceTypes: []api.ResourceType{api.ResourceTypeAny},
		},
		Function: func(fArgs handler.FunctionImplementationArguments) (gaby.Container, any, error) {
			return genericFnSetDefaultNames(resourceProvider, fArgs.FunctionContext, fArgs.ParsedData, fArgs.Arguments)
		},
	})
}

// TODO: Remove if not still useful
// func trimResourceName(resourceName, typeName, spaceName, unitName, separator string) string {
// 	// The type may be used as a suffix
// 	name := strings.TrimSuffix(strings.TrimSuffix(resourceName, typeName), separator)
// 	// The unit and space may be used as prefixes
// 	name = strings.TrimPrefix(strings.TrimPrefix(name, unitName), separator)
// 	name = strings.TrimPrefix(strings.TrimPrefix(name, spaceName), separator)
// 	return name
// }

func genericFnSetDefaultNames(resourceProvider yamlkit.ResourceProvider, functionContext *api.FunctionContext, parsedData gaby.Container, args []api.FunctionArgument) (gaby.Container, any, error) {
	nameValue := args[0].Value.(string)

	visitor := func(doc *gaby.YamlDoc, output any, context yamlkit.VisitorContext, currentValue string) (any, error) {
		// TODO: Support this condition in the string visitor.
		if !strings.Contains(currentValue, yamlkit.PlaceHolderBlockApplyString) {
			return nil, nil
		}
		// We can't replace the placeholder string because reset doesn't restore the original
		// string, it replaces the whole field with the placeholder value. The whole new value
		// for each specific field is expected to be generated by the default name template.
		// Substrings should be targeted using embedded accessors.
		// Once the template strings are made extensible via API they will be easier to customize.
		// newValue := strings.ReplaceAll(currentValue, yamlkit.PlaceHolderBlockApplyString, defaultName)
		pathString := string(context.Path)
		_, err := doc.SetP(nameValue, pathString)
		return nil, errors.Wrap(err, "unable to set value of "+pathString)
	}
	nameConstructors := yamlkit.GetPathRegistryForAttributeName(resourceProvider, api.AttributeNameDefaultName)
	_, err := yamlkit.VisitPaths[string](parsedData, nameConstructors, []any{}, nil, resourceProvider, visitor, false, nil)
	return parsedData, nil, err
}
