// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

package main

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/confighub/sdk/configkit/k8skit"
	"github.com/confighub/sdk/core/configkit/yamlkit"
	"github.com/confighub/sdk/core/function/api"
	"github.com/confighub/sdk/core/workerapi"
)

var k8sCRDSpecCmd = &cobra.Command{
	Use:   "crd-spec <crd-file>",
	Short: "Write the resource-type spec for a CustomResourceDefinition",
	Long:  getK8sCRDSpecHelp(),
	Args:  cobra.ExactArgs(1),
	RunE:  k8sCRDSpecCmdRun,
}

var k8sCRDSpecNoPodSpecMatch bool

func getK8sCRDSpecHelp() string {
	baseHelp := `Read a CustomResourceDefinition and write the resource-type spec for the types it defines.

A spec is what tells ConfigHub how to address the fields of a resource type: which arrays are
keyed and by what, which sibling fields are mutually exclusive, which objects are freeform
maps, which fields cannot change after creation, and where a pod template sits. Without one,
a custom resource's containers are addressed by position, so a protected value moves when
something is inserted ahead of it, and the container and pod functions do not see the type at
all.

Most of that is already in the CRD's own schema, so this reads it rather than asking you to
transcribe it. The output is the stanza to add to the built-in specs; it goes to stdout, and
anything the reader saw but declined to decide goes to stderr.

What a CRD does not say is which of its fields name other resources, what the type's apply
order is, and which types it is interchangeable with. Those are left out for you to add.

One stanza is written per version the CRD declares, because a version is part of a resource
type.

Examples:
` + "```" + `
  # Write the spec for a CRD
  cub k8s crd-spec autoscalingrunnerset-crd.yaml

  # Read from stdin
  kubectl get crd autoscalingrunnersets.actions.github.com -o yaml | cub k8s crd-spec -

  # Declare the arrays inside a pod spec explicitly, instead of embedding the shape
  cub k8s crd-spec my-crd.yaml --no-pod-spec-match

  # As a structured document rather than a stanza to paste
  cub k8s crd-spec my-crd.yaml -o yaml
` + "```" + `
`

	agentContext := `This reads a local file and talks to no server. It does not register anything: the output is
source to commit, and the type is registered when that lands in a release.

The pod-template embed is a structural guess -- an object with a containers array whose items
have a name and an image -- and is marked as one in the output. Confirm it against the CRD
before keeping it, because a wrong embed means wrong merge keys, which is worse than none.`

	return getCommandHelp(baseHelp, agentContext)
}

func init() {
	k8sCRDSpecCmd.Flags().BoolVar(&k8sCRDSpecNoPodSpecMatch, "no-pod-spec-match", false,
		"Do not look for a pod spec; declare the arrays inside one explicitly instead")
	enableOutputFlag(k8sCRDSpecCmd)
	k8sCmd.AddCommand(k8sCRDSpecCmd)
}

func k8sCRDSpecCmdRun(_ *cobra.Command, args []string) error {
	data, err := readCRDInput(args[0])
	if err != nil {
		return err
	}

	options := k8skit.DefaultCRDSpecOptions()
	options.MatchPodSpec = !k8sCRDSpecNoPodSpecMatch
	specs, err := k8skit.SpecsFromCRD(data, options)
	if err != nil {
		return err
	}

	// -o yaml and -o json give the same content as a document rather than as a stanza with the
	// suggestion marked. The embed is folded in, since a structured consumer has nowhere to put
	// a comment saying to confirm it.
	if renderPayload(crdSpecSet(specs)) {
		return nil
	}

	tprintRaw(renderCRDSpecStanzas(specs, args[0]))
	reportCRDSpecNotes(specs)
	return nil
}

func readCRDInput(path string) ([]byte, error) {
	if path == "-" {
		return io.ReadAll(os.Stdin)
	}
	return os.ReadFile(path)
}

// crdSpecSet folds the suggested embeds into the specs, for the structured output forms.
func crdSpecSet(specs []k8skit.CRDSpec) yamlkit.SpecSet {
	set := yamlkit.SpecSet{ToolchainType: workerapi.ToolchainKubernetesYAML}
	for _, generated := range specs {
		spec := generated.Spec
		spec.Embeds = append(spec.Embeds, generated.SuggestedEmbeds...)
		set.ResourceTypes = append(set.ResourceTypes, spec)
	}
	return set
}

// renderCRDSpecStanzas writes the specs in the form and indentation of the built-in spec file,
// so the output is what gets pasted into it. Rendering by hand rather than marshaling is what
// lets the pod-template suggestion carry the comment that says to confirm it.
func renderCRDSpecStanzas(specs []k8skit.CRDSpec, source string) string {
	var out strings.Builder
	fmt.Fprintf(&out, "  # Generated by cub k8s crd-spec from %s.\n", source)
	out.WriteString("  # A CRD does not say which fields name other resources, what the apply order is, or\n")
	out.WriteString("  # which types this is interchangeable with. Add resource-name paths, applyPriority\n")
	out.WriteString("  # and similarityClass by hand.\n")

	for _, generated := range specs {
		spec := generated.Spec
		fmt.Fprintf(&out, "\n  - type: %s\n", spec.Type)
		if spec.Scope != "" {
			fmt.Fprintf(&out, "    scope: %s\n", spec.Scope)
		}
		if len(generated.SuggestedEmbeds) > 0 {
			out.WriteString(renderCRDSpecEmbeds(generated.SuggestedEmbeds))
		}
		if len(spec.MergeKeys) > 0 {
			out.WriteString("    mergeKeys:\n")
			for _, mergeKey := range spec.MergeKeys {
				fmt.Fprintf(&out, "      - {path: %s, key: %s", mergeKey.Path, mergeKey.Key)
				if len(mergeKey.ExtraKeys) > 0 {
					fmt.Fprintf(&out, ", extraKeys: [%s]", strings.Join(mergeKey.ExtraKeys, ", "))
				}
				out.WriteString("}\n")
			}
		}
		if len(spec.ExclusiveFields) > 0 {
			out.WriteString("    exclusiveFields:\n")
			for _, group := range spec.ExclusiveFields {
				fmt.Fprintf(&out, "      - path: %s\n", group.Path)
				fmt.Fprintf(&out, "        members: [%s]\n", strings.Join(group.Members, ", "))
			}
		}
		if len(spec.MapKeyPaths) > 0 {
			out.WriteString("    mapKeyPaths:\n")
			for _, path := range spec.MapKeyPaths {
				fmt.Fprintf(&out, "      - %s\n", path)
			}
		}
		if len(spec.Attributes) > 0 {
			out.WriteString("    attributes:\n")
			for _, attributeName := range sortedAttributeNames(spec.Attributes) {
				fmt.Fprintf(&out, "      %s:\n", attributeName)
				for _, attributePath := range spec.Attributes[attributeName] {
					fmt.Fprintf(&out, "        - {path: %s}\n", attributePath.Path)
				}
			}
		}
	}
	return out.String()
}

func renderCRDSpecEmbeds(embeds []yamlkit.ShapeEmbed) string {
	var out strings.Builder
	out.WriteString("    # SUGGESTED -- confirm this against the CRD before keeping it. The shape below was\n")
	out.WriteString("    # matched structurally: an object carrying a containers array whose items have a name\n")
	out.WriteString("    # and an image. A wrong embed is a wrong merge key, which is worse than none. Re-run\n")
	out.WriteString("    # with --no-pod-spec-match to declare the arrays inside it explicitly instead.\n")
	out.WriteString("    embeds:\n")
	for _, embed := range embeds {
		fmt.Fprintf(&out, "      - {shape: %s, path: %s}\n", embed.Shape, embed.Path)
	}
	return out.String()
}

// sortedAttributeNames orders an attribute map, so the same CRD renders the same way twice.
func sortedAttributeNames(attributes map[api.AttributeName][]yamlkit.AttributePath) []api.AttributeName {
	names := make([]api.AttributeName, 0, len(attributes))
	for name := range attributes {
		names = append(names, name)
	}
	sort.Slice(names, func(i, j int) bool { return names[i] < names[j] })
	return names
}

// reportCRDSpecNotes writes what the reader declined to decide to stderr, so that stdout stays
// the stanza and a redirect of it stays paste-ready.
func reportCRDSpecNotes(specs []k8skit.CRDSpec) {
	for _, generated := range specs {
		for _, note := range generated.Notes {
			fmt.Fprintf(os.Stderr, "%s: %s\n", generated.Spec.Type, note)
		}
	}
}
