#!/usr/bin/env bash
#
# Generate a third-party software notices file for one of the released binaries.
#
# The file lists every third-party Go module linked into the binary together with
# the full text of each module's license, generated from the compiled import graph
# via google/go-licenses so it reflects exactly what is distributed. The same run
# fails if a forbidden or restricted (copyleft) license is linked in, so the
# release workflow uses it as a gate before any binary is published.
#
# Usage, from the repo root:
#   .github/scripts/gen-third-party-licenses.sh <binary> <module-dir> <output>
#   .github/scripts/gen-third-party-licenses.sh cub cmd/cub bin/THIRD_PARTY_LICENSES-cub.txt
#
# Needs a native Go toolchain at least as new as the `toolchain` line in the
# module's go.mod. A toolchain served from the module cache makes go-licenses fail
# with "does not have module info" for stdlib packages (go-licenses issue #128);
# the release workflow sets GOTOOLCHAIN=local so that condition fails loudly.
#
# This script lives under .github/ because everything else at the repo root is
# replaced from confighub/public on every release.

set -euo pipefail

BINARY="${1:?binary name (cub, cub-worker-run)}"
MODULE_DIR="${2:?module directory (cmd/cub, cmd/cub-worker)}"
OUTPUT="${3:?output path}"

# Pinned for reproducible output. Bump deliberately.
GOLICENSES_VERSION="v2.0.1"

# First-party module prefix: our own code, not third-party.
IGNORE="github.com/confighub/sdk"

# License classes that must never be linked into a distributed binary.
# forbidden: e.g. AGPL. restricted: e.g. GPL/LGPL/CDDL, whose source-disclosure
# obligations would attach to the binary.
DISALLOWED_TYPES="forbidden,restricted"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
case "${OUTPUT}" in /*) ;; *) OUTPUT="${REPO_ROOT}/${OUTPUT}" ;; esac
mkdir -p "$(dirname "${OUTPUT}")"

golicenses() {
  # Run the pinned tool without adding it to any go.mod.
  ( cd "${REPO_ROOT}/${MODULE_DIR}" && \
    GOFLAGS=-mod=mod go run "github.com/google/go-licenses/v2@${GOLICENSES_VERSION}" "$@" )
}

tmp="$(mktemp -d)"
trap 'rm -rf "${tmp}"' EXIT

echo "==> ${BINARY}: checking for disallowed license types (${DISALLOWED_TYPES})..."
golicenses check . --ignore "${IGNORE}" --disallowed_types "${DISALLOWED_TYPES}"

echo "==> ${BINARY}: collecting license texts..."
golicenses save . --ignore "${IGNORE}" --save_path "${tmp}/texts" --force

echo "==> ${BINARY}: building summary..."
# CSV columns: module import path, license URL, license type.
golicenses report . --ignore "${IGNORE}" > "${tmp}/summary.csv" 2>/dev/null
sort -o "${tmp}/summary.csv" "${tmp}/summary.csv"

echo "==> ${BINARY}: writing ${OUTPUT}..."
{
  echo "ConfigHub ${BINARY} — Third-Party Software Notices"
  echo "=================================================="
  echo
  echo "The ${BINARY} binary published with this release statically links the"
  echo "third-party open-source Go modules listed below. Each is distributed under"
  echo "its own license, the full text of which is reproduced further down in this"
  echo "file. The module set is the same for every platform build of this release."
  echo "Generated by .github/scripts/gen-third-party-licenses.sh at release time."
  echo
  echo "SUMMARY (module — license type — source)"
  echo "----------------------------------------"
  while IFS=, read -r module url ltype; do
    [ -z "${module}" ] && continue
    printf '  %-55s %-12s %s\n' "${module}" "${ltype}" "${url}"
  done < "${tmp}/summary.csv"
  echo
  echo "================================================================================"
  echo "FULL LICENSE TEXTS"
  echo "================================================================================"

  while IFS=, read -r module url ltype; do
    [ -z "${module}" ] && continue
    echo
    echo "--------------------------------------------------------------------------------"
    echo "Module:  ${module}"
    echo "License: ${ltype}"
    echo "Source:  ${url}"
    echo "--------------------------------------------------------------------------------"
    echo
    # go-licenses preserves the original license filename (LICENSE, COPYING, ...).
    license_file="$(find "${tmp}/texts/${module}" -maxdepth 1 -type f 2>/dev/null | sort | head -1 || true)"
    if [ -n "${license_file}" ] && [ -f "${license_file}" ]; then
      cat "${license_file}"
    else
      echo "[license text not captured — see ${url}]"
    fi
    echo
  done < "${tmp}/summary.csv"
} > "${OUTPUT}"

count="$(grep -c '^Module:' "${OUTPUT}" || true)"
echo "==> ${BINARY}: done. ${OUTPUT} covers ${count} modules."
