// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

// Code generated by go-swagger; DO NOT EDIT.
package space

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListSpacesParams creates a new ListSpacesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListSpacesParams() *ListSpacesParams {
	return &ListSpacesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListSpacesParamsWithTimeout creates a new ListSpacesParams object
// with the ability to set a timeout on a request.
func NewListSpacesParamsWithTimeout(timeout time.Duration) *ListSpacesParams {
	return &ListSpacesParams{
		timeout: timeout,
	}
}

// NewListSpacesParamsWithContext creates a new ListSpacesParams object
// with the ability to set a context for a request.
func NewListSpacesParamsWithContext(ctx context.Context) *ListSpacesParams {
	return &ListSpacesParams{
		Context: ctx,
	}
}

// NewListSpacesParamsWithHTTPClient creates a new ListSpacesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListSpacesParamsWithHTTPClient(client *http.Client) *ListSpacesParams {
	return &ListSpacesParams{
		HTTPClient: client,
	}
}

/*
ListSpacesParams contains all the parameters to send to the API endpoint

	for the list spaces operation.

	Typically these are written to a http.Request.
*/
type ListSpacesParams struct {

	/* Where.

	   Where filter: The specified string is an expression for the purpose of filtering the list of Spaces returned. The expression syntax was inspired by SQL. It supports conjunctions using `AND` of relational expressions of the form *attribute* *operator* *attribute_or_literal*. The attribute names are case-sensitive and PascalCase, as in the JSON encoding. Supported attributes for Space are `CreatedAt`, `UpdatedAt`, `DisplayName`, `Slug`, `OrganizationID`, and `SpaceID`. `Labels` are supported, using a dot notation to specify a particular map key, as in `Labels.environment = 'Prod'`. Strings and integers support the following operators: `<`, `>`, `<=`, `>=`, `=`, `!=`. UUIDs and boolean attributes support equality and inequality only. String literals are quoted with single quotes, such as `Slug = 'us'`. UUID and time literals must be quoted as string literals, as in `'7c61626f-ddbe-41af-93f6-b69f4ab6d308'`. Time literals use the same form as when serialized as JSON, such as: `CreatedAt > '2025-02-18T23:16:34'`. Integer and boolean literals are also supported for attributes of those types. An example conjunction is: `CreatedAt >= '2025-01-07' AND Labels.mykey = 'myvalue'`. The whole string must be query-encoded.
	*/
	Where *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list spaces params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSpacesParams) WithDefaults() *ListSpacesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list spaces params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSpacesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list spaces params
func (o *ListSpacesParams) WithTimeout(timeout time.Duration) *ListSpacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list spaces params
func (o *ListSpacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list spaces params
func (o *ListSpacesParams) WithContext(ctx context.Context) *ListSpacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list spaces params
func (o *ListSpacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list spaces params
func (o *ListSpacesParams) WithHTTPClient(client *http.Client) *ListSpacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list spaces params
func (o *ListSpacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWhere adds the where to the list spaces params
func (o *ListSpacesParams) WithWhere(where *string) *ListSpacesParams {
	o.SetWhere(where)
	return o
}

// SetWhere adds the where to the list spaces params
func (o *ListSpacesParams) SetWhere(where *string) {
	o.Where = where
}

// WriteToRequest writes these params to a swagger request
func (o *ListSpacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Where != nil {

		// query param where
		var qrWhere string

		if o.Where != nil {
			qrWhere = *o.Where
		}
		qWhere := qrWhere
		if qWhere != "" {

			if err := r.SetQueryParam("where", qWhere); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
