// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

// Code generated by go-swagger; DO NOT EDIT.
package set

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/confighub/sdk/openapi/goclient/models"
)

// CreateSetReader is a Reader for the CreateSet structure.
type CreateSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateSetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateSetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateSetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateSetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /space/{space_id}/set] CreateSet", response, response.Code())
	}
}

// NewCreateSetOK creates a CreateSetOK with default headers values
func NewCreateSetOK() *CreateSetOK {
	return &CreateSetOK{}
}

/*
CreateSetOK describes a response with status code 200, with default header values.

OK
*/
type CreateSetOK struct {
	Payload *models.ModelsSet
}

// IsSuccess returns true when this create set o k response has a 2xx status code
func (o *CreateSetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create set o k response has a 3xx status code
func (o *CreateSetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create set o k response has a 4xx status code
func (o *CreateSetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create set o k response has a 5xx status code
func (o *CreateSetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create set o k response a status code equal to that given
func (o *CreateSetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create set o k response
func (o *CreateSetOK) Code() int {
	return 200
}

func (o *CreateSetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /space/{space_id}/set][%d] createSetOK %s", 200, payload)
}

func (o *CreateSetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /space/{space_id}/set][%d] createSetOK %s", 200, payload)
}

func (o *CreateSetOK) GetPayload() *models.ModelsSet {
	return o.Payload
}

func (o *CreateSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsSet)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSetBadRequest creates a CreateSetBadRequest with default headers values
func NewCreateSetBadRequest() *CreateSetBadRequest {
	return &CreateSetBadRequest{}
}

/*
CreateSetBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateSetBadRequest struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this create set bad request response has a 2xx status code
func (o *CreateSetBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create set bad request response has a 3xx status code
func (o *CreateSetBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create set bad request response has a 4xx status code
func (o *CreateSetBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create set bad request response has a 5xx status code
func (o *CreateSetBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create set bad request response a status code equal to that given
func (o *CreateSetBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create set bad request response
func (o *CreateSetBadRequest) Code() int {
	return 400
}

func (o *CreateSetBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /space/{space_id}/set][%d] createSetBadRequest %s", 400, payload)
}

func (o *CreateSetBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /space/{space_id}/set][%d] createSetBadRequest %s", 400, payload)
}

func (o *CreateSetBadRequest) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *CreateSetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSetUnauthorized creates a CreateSetUnauthorized with default headers values
func NewCreateSetUnauthorized() *CreateSetUnauthorized {
	return &CreateSetUnauthorized{}
}

/*
CreateSetUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateSetUnauthorized struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this create set unauthorized response has a 2xx status code
func (o *CreateSetUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create set unauthorized response has a 3xx status code
func (o *CreateSetUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create set unauthorized response has a 4xx status code
func (o *CreateSetUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create set unauthorized response has a 5xx status code
func (o *CreateSetUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create set unauthorized response a status code equal to that given
func (o *CreateSetUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create set unauthorized response
func (o *CreateSetUnauthorized) Code() int {
	return 401
}

func (o *CreateSetUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /space/{space_id}/set][%d] createSetUnauthorized %s", 401, payload)
}

func (o *CreateSetUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /space/{space_id}/set][%d] createSetUnauthorized %s", 401, payload)
}

func (o *CreateSetUnauthorized) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *CreateSetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSetForbidden creates a CreateSetForbidden with default headers values
func NewCreateSetForbidden() *CreateSetForbidden {
	return &CreateSetForbidden{}
}

/*
CreateSetForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateSetForbidden struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this create set forbidden response has a 2xx status code
func (o *CreateSetForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create set forbidden response has a 3xx status code
func (o *CreateSetForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create set forbidden response has a 4xx status code
func (o *CreateSetForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create set forbidden response has a 5xx status code
func (o *CreateSetForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create set forbidden response a status code equal to that given
func (o *CreateSetForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create set forbidden response
func (o *CreateSetForbidden) Code() int {
	return 403
}

func (o *CreateSetForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /space/{space_id}/set][%d] createSetForbidden %s", 403, payload)
}

func (o *CreateSetForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /space/{space_id}/set][%d] createSetForbidden %s", 403, payload)
}

func (o *CreateSetForbidden) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *CreateSetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSetInternalServerError creates a CreateSetInternalServerError with default headers values
func NewCreateSetInternalServerError() *CreateSetInternalServerError {
	return &CreateSetInternalServerError{}
}

/*
CreateSetInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateSetInternalServerError struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this create set internal server error response has a 2xx status code
func (o *CreateSetInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create set internal server error response has a 3xx status code
func (o *CreateSetInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create set internal server error response has a 4xx status code
func (o *CreateSetInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create set internal server error response has a 5xx status code
func (o *CreateSetInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create set internal server error response a status code equal to that given
func (o *CreateSetInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create set internal server error response
func (o *CreateSetInternalServerError) Code() int {
	return 500
}

func (o *CreateSetInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /space/{space_id}/set][%d] createSetInternalServerError %s", 500, payload)
}

func (o *CreateSetInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /space/{space_id}/set][%d] createSetInternalServerError %s", 500, payload)
}

func (o *CreateSetInternalServerError) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *CreateSetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
