// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

// Code generated by go-swagger; DO NOT EDIT.
package set

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSetExtendedParams creates a new GetSetExtendedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSetExtendedParams() *GetSetExtendedParams {
	return &GetSetExtendedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSetExtendedParamsWithTimeout creates a new GetSetExtendedParams object
// with the ability to set a timeout on a request.
func NewGetSetExtendedParamsWithTimeout(timeout time.Duration) *GetSetExtendedParams {
	return &GetSetExtendedParams{
		timeout: timeout,
	}
}

// NewGetSetExtendedParamsWithContext creates a new GetSetExtendedParams object
// with the ability to set a context for a request.
func NewGetSetExtendedParamsWithContext(ctx context.Context) *GetSetExtendedParams {
	return &GetSetExtendedParams{
		Context: ctx,
	}
}

// NewGetSetExtendedParamsWithHTTPClient creates a new GetSetExtendedParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSetExtendedParamsWithHTTPClient(client *http.Client) *GetSetExtendedParams {
	return &GetSetExtendedParams{
		HTTPClient: client,
	}
}

/*
GetSetExtendedParams contains all the parameters to send to the API endpoint

	for the get set extended operation.

	Typically these are written to a http.Request.
*/
type GetSetExtendedParams struct {

	/* SetID.

	   Set ID
	*/
	SetID string

	/* SpaceID.

	   Space ID
	*/
	SpaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get set extended params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSetExtendedParams) WithDefaults() *GetSetExtendedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get set extended params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSetExtendedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get set extended params
func (o *GetSetExtendedParams) WithTimeout(timeout time.Duration) *GetSetExtendedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get set extended params
func (o *GetSetExtendedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get set extended params
func (o *GetSetExtendedParams) WithContext(ctx context.Context) *GetSetExtendedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get set extended params
func (o *GetSetExtendedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get set extended params
func (o *GetSetExtendedParams) WithHTTPClient(client *http.Client) *GetSetExtendedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get set extended params
func (o *GetSetExtendedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSetID adds the setID to the get set extended params
func (o *GetSetExtendedParams) WithSetID(setID string) *GetSetExtendedParams {
	o.SetSetID(setID)
	return o
}

// SetSetID adds the setId to the get set extended params
func (o *GetSetExtendedParams) SetSetID(setID string) {
	o.SetID = setID
}

// WithSpaceID adds the spaceID to the get set extended params
func (o *GetSetExtendedParams) WithSpaceID(spaceID string) *GetSetExtendedParams {
	o.SetSpaceID(spaceID)
	return o
}

// SetSpaceID adds the spaceId to the get set extended params
func (o *GetSetExtendedParams) SetSpaceID(spaceID string) {
	o.SpaceID = spaceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetSetExtendedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param set_id
	if err := r.SetPathParam("set_id", o.SetID); err != nil {
		return err
	}

	// path param space_id
	if err := r.SetPathParam("space_id", o.SpaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
