// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

// Code generated by go-swagger; DO NOT EDIT.
package unit_event

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUnitEventParams creates a new GetUnitEventParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUnitEventParams() *GetUnitEventParams {
	return &GetUnitEventParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUnitEventParamsWithTimeout creates a new GetUnitEventParams object
// with the ability to set a timeout on a request.
func NewGetUnitEventParamsWithTimeout(timeout time.Duration) *GetUnitEventParams {
	return &GetUnitEventParams{
		timeout: timeout,
	}
}

// NewGetUnitEventParamsWithContext creates a new GetUnitEventParams object
// with the ability to set a context for a request.
func NewGetUnitEventParamsWithContext(ctx context.Context) *GetUnitEventParams {
	return &GetUnitEventParams{
		Context: ctx,
	}
}

// NewGetUnitEventParamsWithHTTPClient creates a new GetUnitEventParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUnitEventParamsWithHTTPClient(client *http.Client) *GetUnitEventParams {
	return &GetUnitEventParams{
		HTTPClient: client,
	}
}

/*
GetUnitEventParams contains all the parameters to send to the API endpoint

	for the get unit event operation.

	Typically these are written to a http.Request.
*/
type GetUnitEventParams struct {

	/* SpaceID.

	   Space ID
	*/
	SpaceID string

	/* UnitEventID.

	   Unit Event ID
	*/
	UnitEventID string

	/* UnitID.

	   Unit ID
	*/
	UnitID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get unit event params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUnitEventParams) WithDefaults() *GetUnitEventParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get unit event params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUnitEventParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get unit event params
func (o *GetUnitEventParams) WithTimeout(timeout time.Duration) *GetUnitEventParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get unit event params
func (o *GetUnitEventParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get unit event params
func (o *GetUnitEventParams) WithContext(ctx context.Context) *GetUnitEventParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get unit event params
func (o *GetUnitEventParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get unit event params
func (o *GetUnitEventParams) WithHTTPClient(client *http.Client) *GetUnitEventParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get unit event params
func (o *GetUnitEventParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSpaceID adds the spaceID to the get unit event params
func (o *GetUnitEventParams) WithSpaceID(spaceID string) *GetUnitEventParams {
	o.SetSpaceID(spaceID)
	return o
}

// SetSpaceID adds the spaceId to the get unit event params
func (o *GetUnitEventParams) SetSpaceID(spaceID string) {
	o.SpaceID = spaceID
}

// WithUnitEventID adds the unitEventID to the get unit event params
func (o *GetUnitEventParams) WithUnitEventID(unitEventID string) *GetUnitEventParams {
	o.SetUnitEventID(unitEventID)
	return o
}

// SetUnitEventID adds the unitEventId to the get unit event params
func (o *GetUnitEventParams) SetUnitEventID(unitEventID string) {
	o.UnitEventID = unitEventID
}

// WithUnitID adds the unitID to the get unit event params
func (o *GetUnitEventParams) WithUnitID(unitID string) *GetUnitEventParams {
	o.SetUnitID(unitID)
	return o
}

// SetUnitID adds the unitId to the get unit event params
func (o *GetUnitEventParams) SetUnitID(unitID string) {
	o.UnitID = unitID
}

// WriteToRequest writes these params to a swagger request
func (o *GetUnitEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param space_id
	if err := r.SetPathParam("space_id", o.SpaceID); err != nil {
		return err
	}

	// path param unit_event_id
	if err := r.SetPathParam("unit_event_id", o.UnitEventID); err != nil {
		return err
	}

	// path param unit_id
	if err := r.SetPathParam("unit_id", o.UnitID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
