// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

// Code generated by go-swagger; DO NOT EDIT.
package trigger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTriggerExtendedParams creates a new GetTriggerExtendedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTriggerExtendedParams() *GetTriggerExtendedParams {
	return &GetTriggerExtendedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTriggerExtendedParamsWithTimeout creates a new GetTriggerExtendedParams object
// with the ability to set a timeout on a request.
func NewGetTriggerExtendedParamsWithTimeout(timeout time.Duration) *GetTriggerExtendedParams {
	return &GetTriggerExtendedParams{
		timeout: timeout,
	}
}

// NewGetTriggerExtendedParamsWithContext creates a new GetTriggerExtendedParams object
// with the ability to set a context for a request.
func NewGetTriggerExtendedParamsWithContext(ctx context.Context) *GetTriggerExtendedParams {
	return &GetTriggerExtendedParams{
		Context: ctx,
	}
}

// NewGetTriggerExtendedParamsWithHTTPClient creates a new GetTriggerExtendedParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTriggerExtendedParamsWithHTTPClient(client *http.Client) *GetTriggerExtendedParams {
	return &GetTriggerExtendedParams{
		HTTPClient: client,
	}
}

/*
GetTriggerExtendedParams contains all the parameters to send to the API endpoint

	for the get trigger extended operation.

	Typically these are written to a http.Request.
*/
type GetTriggerExtendedParams struct {

	/* SpaceID.

	   Space ID
	*/
	SpaceID string

	/* TriggerID.

	   Trigger ID
	*/
	TriggerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get trigger extended params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTriggerExtendedParams) WithDefaults() *GetTriggerExtendedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get trigger extended params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTriggerExtendedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get trigger extended params
func (o *GetTriggerExtendedParams) WithTimeout(timeout time.Duration) *GetTriggerExtendedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get trigger extended params
func (o *GetTriggerExtendedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get trigger extended params
func (o *GetTriggerExtendedParams) WithContext(ctx context.Context) *GetTriggerExtendedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get trigger extended params
func (o *GetTriggerExtendedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get trigger extended params
func (o *GetTriggerExtendedParams) WithHTTPClient(client *http.Client) *GetTriggerExtendedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get trigger extended params
func (o *GetTriggerExtendedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSpaceID adds the spaceID to the get trigger extended params
func (o *GetTriggerExtendedParams) WithSpaceID(spaceID string) *GetTriggerExtendedParams {
	o.SetSpaceID(spaceID)
	return o
}

// SetSpaceID adds the spaceId to the get trigger extended params
func (o *GetTriggerExtendedParams) SetSpaceID(spaceID string) {
	o.SpaceID = spaceID
}

// WithTriggerID adds the triggerID to the get trigger extended params
func (o *GetTriggerExtendedParams) WithTriggerID(triggerID string) *GetTriggerExtendedParams {
	o.SetTriggerID(triggerID)
	return o
}

// SetTriggerID adds the triggerId to the get trigger extended params
func (o *GetTriggerExtendedParams) SetTriggerID(triggerID string) {
	o.TriggerID = triggerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetTriggerExtendedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param space_id
	if err := r.SetPathParam("space_id", o.SpaceID); err != nil {
		return err
	}

	// path param trigger_id
	if err := r.SetPathParam("trigger_id", o.TriggerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
