// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

// Code generated by go-swagger; DO NOT EDIT.
package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/confighub/sdk/openapi/goclient/models"
)

// GetOrganizationMemberReader is a Reader for the GetOrganizationMember structure.
type GetOrganizationMemberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationMemberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationMemberOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetOrganizationMemberBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetOrganizationMemberUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetOrganizationMemberForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetOrganizationMemberNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetOrganizationMemberInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /organization/{organization_id}/organization_member/{organization_member_id}] GetOrganizationMember", response, response.Code())
	}
}

// NewGetOrganizationMemberOK creates a GetOrganizationMemberOK with default headers values
func NewGetOrganizationMemberOK() *GetOrganizationMemberOK {
	return &GetOrganizationMemberOK{}
}

/*
GetOrganizationMemberOK describes a response with status code 200, with default header values.

OK
*/
type GetOrganizationMemberOK struct {
	Payload *models.ModelsOrganizationMember
}

// IsSuccess returns true when this get organization member o k response has a 2xx status code
func (o *GetOrganizationMemberOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get organization member o k response has a 3xx status code
func (o *GetOrganizationMemberOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization member o k response has a 4xx status code
func (o *GetOrganizationMemberOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get organization member o k response has a 5xx status code
func (o *GetOrganizationMemberOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization member o k response a status code equal to that given
func (o *GetOrganizationMemberOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get organization member o k response
func (o *GetOrganizationMemberOK) Code() int {
	return 200
}

func (o *GetOrganizationMemberOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}/organization_member/{organization_member_id}][%d] getOrganizationMemberOK %s", 200, payload)
}

func (o *GetOrganizationMemberOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}/organization_member/{organization_member_id}][%d] getOrganizationMemberOK %s", 200, payload)
}

func (o *GetOrganizationMemberOK) GetPayload() *models.ModelsOrganizationMember {
	return o.Payload
}

func (o *GetOrganizationMemberOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsOrganizationMember)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationMemberBadRequest creates a GetOrganizationMemberBadRequest with default headers values
func NewGetOrganizationMemberBadRequest() *GetOrganizationMemberBadRequest {
	return &GetOrganizationMemberBadRequest{}
}

/*
GetOrganizationMemberBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetOrganizationMemberBadRequest struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this get organization member bad request response has a 2xx status code
func (o *GetOrganizationMemberBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get organization member bad request response has a 3xx status code
func (o *GetOrganizationMemberBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization member bad request response has a 4xx status code
func (o *GetOrganizationMemberBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get organization member bad request response has a 5xx status code
func (o *GetOrganizationMemberBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization member bad request response a status code equal to that given
func (o *GetOrganizationMemberBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get organization member bad request response
func (o *GetOrganizationMemberBadRequest) Code() int {
	return 400
}

func (o *GetOrganizationMemberBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}/organization_member/{organization_member_id}][%d] getOrganizationMemberBadRequest %s", 400, payload)
}

func (o *GetOrganizationMemberBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}/organization_member/{organization_member_id}][%d] getOrganizationMemberBadRequest %s", 400, payload)
}

func (o *GetOrganizationMemberBadRequest) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *GetOrganizationMemberBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationMemberUnauthorized creates a GetOrganizationMemberUnauthorized with default headers values
func NewGetOrganizationMemberUnauthorized() *GetOrganizationMemberUnauthorized {
	return &GetOrganizationMemberUnauthorized{}
}

/*
GetOrganizationMemberUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetOrganizationMemberUnauthorized struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this get organization member unauthorized response has a 2xx status code
func (o *GetOrganizationMemberUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get organization member unauthorized response has a 3xx status code
func (o *GetOrganizationMemberUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization member unauthorized response has a 4xx status code
func (o *GetOrganizationMemberUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get organization member unauthorized response has a 5xx status code
func (o *GetOrganizationMemberUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization member unauthorized response a status code equal to that given
func (o *GetOrganizationMemberUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get organization member unauthorized response
func (o *GetOrganizationMemberUnauthorized) Code() int {
	return 401
}

func (o *GetOrganizationMemberUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}/organization_member/{organization_member_id}][%d] getOrganizationMemberUnauthorized %s", 401, payload)
}

func (o *GetOrganizationMemberUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}/organization_member/{organization_member_id}][%d] getOrganizationMemberUnauthorized %s", 401, payload)
}

func (o *GetOrganizationMemberUnauthorized) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *GetOrganizationMemberUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationMemberForbidden creates a GetOrganizationMemberForbidden with default headers values
func NewGetOrganizationMemberForbidden() *GetOrganizationMemberForbidden {
	return &GetOrganizationMemberForbidden{}
}

/*
GetOrganizationMemberForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetOrganizationMemberForbidden struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this get organization member forbidden response has a 2xx status code
func (o *GetOrganizationMemberForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get organization member forbidden response has a 3xx status code
func (o *GetOrganizationMemberForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization member forbidden response has a 4xx status code
func (o *GetOrganizationMemberForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get organization member forbidden response has a 5xx status code
func (o *GetOrganizationMemberForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization member forbidden response a status code equal to that given
func (o *GetOrganizationMemberForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get organization member forbidden response
func (o *GetOrganizationMemberForbidden) Code() int {
	return 403
}

func (o *GetOrganizationMemberForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}/organization_member/{organization_member_id}][%d] getOrganizationMemberForbidden %s", 403, payload)
}

func (o *GetOrganizationMemberForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}/organization_member/{organization_member_id}][%d] getOrganizationMemberForbidden %s", 403, payload)
}

func (o *GetOrganizationMemberForbidden) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *GetOrganizationMemberForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationMemberNotFound creates a GetOrganizationMemberNotFound with default headers values
func NewGetOrganizationMemberNotFound() *GetOrganizationMemberNotFound {
	return &GetOrganizationMemberNotFound{}
}

/*
GetOrganizationMemberNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetOrganizationMemberNotFound struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this get organization member not found response has a 2xx status code
func (o *GetOrganizationMemberNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get organization member not found response has a 3xx status code
func (o *GetOrganizationMemberNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization member not found response has a 4xx status code
func (o *GetOrganizationMemberNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get organization member not found response has a 5xx status code
func (o *GetOrganizationMemberNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization member not found response a status code equal to that given
func (o *GetOrganizationMemberNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get organization member not found response
func (o *GetOrganizationMemberNotFound) Code() int {
	return 404
}

func (o *GetOrganizationMemberNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}/organization_member/{organization_member_id}][%d] getOrganizationMemberNotFound %s", 404, payload)
}

func (o *GetOrganizationMemberNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}/organization_member/{organization_member_id}][%d] getOrganizationMemberNotFound %s", 404, payload)
}

func (o *GetOrganizationMemberNotFound) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *GetOrganizationMemberNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationMemberInternalServerError creates a GetOrganizationMemberInternalServerError with default headers values
func NewGetOrganizationMemberInternalServerError() *GetOrganizationMemberInternalServerError {
	return &GetOrganizationMemberInternalServerError{}
}

/*
GetOrganizationMemberInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetOrganizationMemberInternalServerError struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this get organization member internal server error response has a 2xx status code
func (o *GetOrganizationMemberInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get organization member internal server error response has a 3xx status code
func (o *GetOrganizationMemberInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization member internal server error response has a 4xx status code
func (o *GetOrganizationMemberInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get organization member internal server error response has a 5xx status code
func (o *GetOrganizationMemberInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get organization member internal server error response a status code equal to that given
func (o *GetOrganizationMemberInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get organization member internal server error response
func (o *GetOrganizationMemberInternalServerError) Code() int {
	return 500
}

func (o *GetOrganizationMemberInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}/organization_member/{organization_member_id}][%d] getOrganizationMemberInternalServerError %s", 500, payload)
}

func (o *GetOrganizationMemberInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}/organization_member/{organization_member_id}][%d] getOrganizationMemberInternalServerError %s", 500, payload)
}

func (o *GetOrganizationMemberInternalServerError) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *GetOrganizationMemberInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
