// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

// Code generated by go-swagger; DO NOT EDIT.
package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/confighub/sdk/openapi/goclient/models"
)

// GetOrganizationReader is a Reader for the GetOrganization structure.
type GetOrganizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetOrganizationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetOrganizationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetOrganizationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetOrganizationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetOrganizationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /organization/{organization_id}] GetOrganization", response, response.Code())
	}
}

// NewGetOrganizationOK creates a GetOrganizationOK with default headers values
func NewGetOrganizationOK() *GetOrganizationOK {
	return &GetOrganizationOK{}
}

/*
GetOrganizationOK describes a response with status code 200, with default header values.

OK
*/
type GetOrganizationOK struct {
	Payload *models.ModelsOrganization
}

// IsSuccess returns true when this get organization o k response has a 2xx status code
func (o *GetOrganizationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get organization o k response has a 3xx status code
func (o *GetOrganizationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization o k response has a 4xx status code
func (o *GetOrganizationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get organization o k response has a 5xx status code
func (o *GetOrganizationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization o k response a status code equal to that given
func (o *GetOrganizationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get organization o k response
func (o *GetOrganizationOK) Code() int {
	return 200
}

func (o *GetOrganizationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}][%d] getOrganizationOK %s", 200, payload)
}

func (o *GetOrganizationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}][%d] getOrganizationOK %s", 200, payload)
}

func (o *GetOrganizationOK) GetPayload() *models.ModelsOrganization {
	return o.Payload
}

func (o *GetOrganizationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsOrganization)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationBadRequest creates a GetOrganizationBadRequest with default headers values
func NewGetOrganizationBadRequest() *GetOrganizationBadRequest {
	return &GetOrganizationBadRequest{}
}

/*
GetOrganizationBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetOrganizationBadRequest struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this get organization bad request response has a 2xx status code
func (o *GetOrganizationBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get organization bad request response has a 3xx status code
func (o *GetOrganizationBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization bad request response has a 4xx status code
func (o *GetOrganizationBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get organization bad request response has a 5xx status code
func (o *GetOrganizationBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization bad request response a status code equal to that given
func (o *GetOrganizationBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get organization bad request response
func (o *GetOrganizationBadRequest) Code() int {
	return 400
}

func (o *GetOrganizationBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}][%d] getOrganizationBadRequest %s", 400, payload)
}

func (o *GetOrganizationBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}][%d] getOrganizationBadRequest %s", 400, payload)
}

func (o *GetOrganizationBadRequest) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *GetOrganizationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationUnauthorized creates a GetOrganizationUnauthorized with default headers values
func NewGetOrganizationUnauthorized() *GetOrganizationUnauthorized {
	return &GetOrganizationUnauthorized{}
}

/*
GetOrganizationUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetOrganizationUnauthorized struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this get organization unauthorized response has a 2xx status code
func (o *GetOrganizationUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get organization unauthorized response has a 3xx status code
func (o *GetOrganizationUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization unauthorized response has a 4xx status code
func (o *GetOrganizationUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get organization unauthorized response has a 5xx status code
func (o *GetOrganizationUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization unauthorized response a status code equal to that given
func (o *GetOrganizationUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get organization unauthorized response
func (o *GetOrganizationUnauthorized) Code() int {
	return 401
}

func (o *GetOrganizationUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}][%d] getOrganizationUnauthorized %s", 401, payload)
}

func (o *GetOrganizationUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}][%d] getOrganizationUnauthorized %s", 401, payload)
}

func (o *GetOrganizationUnauthorized) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *GetOrganizationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationForbidden creates a GetOrganizationForbidden with default headers values
func NewGetOrganizationForbidden() *GetOrganizationForbidden {
	return &GetOrganizationForbidden{}
}

/*
GetOrganizationForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetOrganizationForbidden struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this get organization forbidden response has a 2xx status code
func (o *GetOrganizationForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get organization forbidden response has a 3xx status code
func (o *GetOrganizationForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization forbidden response has a 4xx status code
func (o *GetOrganizationForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get organization forbidden response has a 5xx status code
func (o *GetOrganizationForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization forbidden response a status code equal to that given
func (o *GetOrganizationForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get organization forbidden response
func (o *GetOrganizationForbidden) Code() int {
	return 403
}

func (o *GetOrganizationForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}][%d] getOrganizationForbidden %s", 403, payload)
}

func (o *GetOrganizationForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}][%d] getOrganizationForbidden %s", 403, payload)
}

func (o *GetOrganizationForbidden) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *GetOrganizationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationNotFound creates a GetOrganizationNotFound with default headers values
func NewGetOrganizationNotFound() *GetOrganizationNotFound {
	return &GetOrganizationNotFound{}
}

/*
GetOrganizationNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetOrganizationNotFound struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this get organization not found response has a 2xx status code
func (o *GetOrganizationNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get organization not found response has a 3xx status code
func (o *GetOrganizationNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization not found response has a 4xx status code
func (o *GetOrganizationNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get organization not found response has a 5xx status code
func (o *GetOrganizationNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization not found response a status code equal to that given
func (o *GetOrganizationNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get organization not found response
func (o *GetOrganizationNotFound) Code() int {
	return 404
}

func (o *GetOrganizationNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}][%d] getOrganizationNotFound %s", 404, payload)
}

func (o *GetOrganizationNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}][%d] getOrganizationNotFound %s", 404, payload)
}

func (o *GetOrganizationNotFound) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *GetOrganizationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationInternalServerError creates a GetOrganizationInternalServerError with default headers values
func NewGetOrganizationInternalServerError() *GetOrganizationInternalServerError {
	return &GetOrganizationInternalServerError{}
}

/*
GetOrganizationInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetOrganizationInternalServerError struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this get organization internal server error response has a 2xx status code
func (o *GetOrganizationInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get organization internal server error response has a 3xx status code
func (o *GetOrganizationInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization internal server error response has a 4xx status code
func (o *GetOrganizationInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get organization internal server error response has a 5xx status code
func (o *GetOrganizationInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get organization internal server error response a status code equal to that given
func (o *GetOrganizationInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get organization internal server error response
func (o *GetOrganizationInternalServerError) Code() int {
	return 500
}

func (o *GetOrganizationInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}][%d] getOrganizationInternalServerError %s", 500, payload)
}

func (o *GetOrganizationInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organization/{organization_id}][%d] getOrganizationInternalServerError %s", 500, payload)
}

func (o *GetOrganizationInternalServerError) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *GetOrganizationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
