// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

// Code generated by go-swagger; DO NOT EDIT.
package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/confighub/sdk/openapi/goclient/models"
)

// UpdateOrganizationReader is a Reader for the UpdateOrganization structure.
type UpdateOrganizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateOrganizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateOrganizationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateOrganizationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateOrganizationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateOrganizationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateOrganizationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateOrganizationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /organization/{organization_id}] UpdateOrganization", response, response.Code())
	}
}

// NewUpdateOrganizationOK creates a UpdateOrganizationOK with default headers values
func NewUpdateOrganizationOK() *UpdateOrganizationOK {
	return &UpdateOrganizationOK{}
}

/*
UpdateOrganizationOK describes a response with status code 200, with default header values.

OK
*/
type UpdateOrganizationOK struct {
	Payload *models.ModelsOrganization
}

// IsSuccess returns true when this update organization o k response has a 2xx status code
func (o *UpdateOrganizationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update organization o k response has a 3xx status code
func (o *UpdateOrganizationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update organization o k response has a 4xx status code
func (o *UpdateOrganizationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update organization o k response has a 5xx status code
func (o *UpdateOrganizationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update organization o k response a status code equal to that given
func (o *UpdateOrganizationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update organization o k response
func (o *UpdateOrganizationOK) Code() int {
	return 200
}

func (o *UpdateOrganizationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /organization/{organization_id}][%d] updateOrganizationOK %s", 200, payload)
}

func (o *UpdateOrganizationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /organization/{organization_id}][%d] updateOrganizationOK %s", 200, payload)
}

func (o *UpdateOrganizationOK) GetPayload() *models.ModelsOrganization {
	return o.Payload
}

func (o *UpdateOrganizationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsOrganization)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateOrganizationBadRequest creates a UpdateOrganizationBadRequest with default headers values
func NewUpdateOrganizationBadRequest() *UpdateOrganizationBadRequest {
	return &UpdateOrganizationBadRequest{}
}

/*
UpdateOrganizationBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UpdateOrganizationBadRequest struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this update organization bad request response has a 2xx status code
func (o *UpdateOrganizationBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update organization bad request response has a 3xx status code
func (o *UpdateOrganizationBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update organization bad request response has a 4xx status code
func (o *UpdateOrganizationBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update organization bad request response has a 5xx status code
func (o *UpdateOrganizationBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update organization bad request response a status code equal to that given
func (o *UpdateOrganizationBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update organization bad request response
func (o *UpdateOrganizationBadRequest) Code() int {
	return 400
}

func (o *UpdateOrganizationBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /organization/{organization_id}][%d] updateOrganizationBadRequest %s", 400, payload)
}

func (o *UpdateOrganizationBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /organization/{organization_id}][%d] updateOrganizationBadRequest %s", 400, payload)
}

func (o *UpdateOrganizationBadRequest) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *UpdateOrganizationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateOrganizationUnauthorized creates a UpdateOrganizationUnauthorized with default headers values
func NewUpdateOrganizationUnauthorized() *UpdateOrganizationUnauthorized {
	return &UpdateOrganizationUnauthorized{}
}

/*
UpdateOrganizationUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type UpdateOrganizationUnauthorized struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this update organization unauthorized response has a 2xx status code
func (o *UpdateOrganizationUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update organization unauthorized response has a 3xx status code
func (o *UpdateOrganizationUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update organization unauthorized response has a 4xx status code
func (o *UpdateOrganizationUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this update organization unauthorized response has a 5xx status code
func (o *UpdateOrganizationUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this update organization unauthorized response a status code equal to that given
func (o *UpdateOrganizationUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the update organization unauthorized response
func (o *UpdateOrganizationUnauthorized) Code() int {
	return 401
}

func (o *UpdateOrganizationUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /organization/{organization_id}][%d] updateOrganizationUnauthorized %s", 401, payload)
}

func (o *UpdateOrganizationUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /organization/{organization_id}][%d] updateOrganizationUnauthorized %s", 401, payload)
}

func (o *UpdateOrganizationUnauthorized) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *UpdateOrganizationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateOrganizationForbidden creates a UpdateOrganizationForbidden with default headers values
func NewUpdateOrganizationForbidden() *UpdateOrganizationForbidden {
	return &UpdateOrganizationForbidden{}
}

/*
UpdateOrganizationForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type UpdateOrganizationForbidden struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this update organization forbidden response has a 2xx status code
func (o *UpdateOrganizationForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update organization forbidden response has a 3xx status code
func (o *UpdateOrganizationForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update organization forbidden response has a 4xx status code
func (o *UpdateOrganizationForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this update organization forbidden response has a 5xx status code
func (o *UpdateOrganizationForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this update organization forbidden response a status code equal to that given
func (o *UpdateOrganizationForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the update organization forbidden response
func (o *UpdateOrganizationForbidden) Code() int {
	return 403
}

func (o *UpdateOrganizationForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /organization/{organization_id}][%d] updateOrganizationForbidden %s", 403, payload)
}

func (o *UpdateOrganizationForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /organization/{organization_id}][%d] updateOrganizationForbidden %s", 403, payload)
}

func (o *UpdateOrganizationForbidden) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *UpdateOrganizationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateOrganizationNotFound creates a UpdateOrganizationNotFound with default headers values
func NewUpdateOrganizationNotFound() *UpdateOrganizationNotFound {
	return &UpdateOrganizationNotFound{}
}

/*
UpdateOrganizationNotFound describes a response with status code 404, with default header values.

Not Found
*/
type UpdateOrganizationNotFound struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this update organization not found response has a 2xx status code
func (o *UpdateOrganizationNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update organization not found response has a 3xx status code
func (o *UpdateOrganizationNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update organization not found response has a 4xx status code
func (o *UpdateOrganizationNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update organization not found response has a 5xx status code
func (o *UpdateOrganizationNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update organization not found response a status code equal to that given
func (o *UpdateOrganizationNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update organization not found response
func (o *UpdateOrganizationNotFound) Code() int {
	return 404
}

func (o *UpdateOrganizationNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /organization/{organization_id}][%d] updateOrganizationNotFound %s", 404, payload)
}

func (o *UpdateOrganizationNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /organization/{organization_id}][%d] updateOrganizationNotFound %s", 404, payload)
}

func (o *UpdateOrganizationNotFound) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *UpdateOrganizationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateOrganizationInternalServerError creates a UpdateOrganizationInternalServerError with default headers values
func NewUpdateOrganizationInternalServerError() *UpdateOrganizationInternalServerError {
	return &UpdateOrganizationInternalServerError{}
}

/*
UpdateOrganizationInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type UpdateOrganizationInternalServerError struct {
	Payload *models.ModelsErrorMessage
}

// IsSuccess returns true when this update organization internal server error response has a 2xx status code
func (o *UpdateOrganizationInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update organization internal server error response has a 3xx status code
func (o *UpdateOrganizationInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update organization internal server error response has a 4xx status code
func (o *UpdateOrganizationInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this update organization internal server error response has a 5xx status code
func (o *UpdateOrganizationInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this update organization internal server error response a status code equal to that given
func (o *UpdateOrganizationInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the update organization internal server error response
func (o *UpdateOrganizationInternalServerError) Code() int {
	return 500
}

func (o *UpdateOrganizationInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /organization/{organization_id}][%d] updateOrganizationInternalServerError %s", 500, payload)
}

func (o *UpdateOrganizationInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /organization/{organization_id}][%d] updateOrganizationInternalServerError %s", 500, payload)
}

func (o *UpdateOrganizationInternalServerError) GetPayload() *models.ModelsErrorMessage {
	return o.Payload
}

func (o *UpdateOrganizationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
