// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

// Code generated by go-swagger; DO NOT EDIT.
package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIFunctionParameter api function parameter
//
// swagger:model api.FunctionParameter
type APIFunctionParameter struct {

	// data type
	DataType string `json:"DataType,omitempty"`

	// description
	Description string `json:"Description,omitempty"`

	// parameter name
	ParameterName string `json:"ParameterName,omitempty"`

	// required
	Required bool `json:"Required,omitempty"`
}

// Validate validates this api function parameter
func (m *APIFunctionParameter) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api function parameter based on context it is used
func (m *APIFunctionParameter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIFunctionParameter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIFunctionParameter) UnmarshalBinary(b []byte) error {
	var res APIFunctionParameter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
