// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

// Code generated by go-swagger; DO NOT EDIT.
package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ContractsAPIInfo contracts Api info
//
// swagger:model contracts.ApiInfo
type ContractsAPIInfo struct {

	// build
	Build string `json:"Build,omitempty"`

	// client ID
	ClientID string `json:"ClientID,omitempty"`
}

// Validate validates this contracts Api info
func (m *ContractsAPIInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this contracts Api info based on context it is used
func (m *ContractsAPIInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ContractsAPIInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContractsAPIInfo) UnmarshalBinary(b []byte) error {
	var res ContractsAPIInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
