// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

// Code generated by go-swagger; DO NOT EDIT.
package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsTarget models target
//
// swagger:model models.Target
type ModelsTarget struct {

	// annotations
	Annotations map[string]string `json:"Annotations,omitempty"`

	// BridgeWorkerID is the identifier of the associated bridge worker that will
	// handle actions for this target.
	// required: true
	// example: "123e4567-e89b-12d3-a456-426614174001"
	BridgeWorkerID string `json:"BridgeWorkerID,omitempty"`

	// CreatedAt is the timestamp when the entity was created in "2023-01-01T12:00:00Z" format.
	// Example: 2025-04-04T11:50:02.95102-07:00
	CreatedAt string `json:"CreatedAt,omitempty"`

	// CursorID is an auto-incrementing sequence number used for pagination.
	CursorID int64 `json:"CursorID,omitempty"`

	// not URL-safe
	DisplayName string `json:"DisplayName,omitempty"`

	// labels
	Labels map[string]string `json:"Labels,omitempty"`

	// Child ID uniqueness is scoped to an organization
	OrganizationID string `json:"OrganizationID,omitempty"`

	// Parameters contains plugin-specific configuration parameters in JSON format
	Parameters string `json:"Parameters,omitempty"`

	// ProviderType specifies the cloud or infrastructure provider for this target.
	// required: true
	// example: "Kubernetes"
	ProviderType string `json:"ProviderType,omitempty"`

	// URL-safe; must be unique within the same container hierarchy
	Slug string `json:"Slug,omitempty"`

	// space ID
	SpaceID string `json:"SpaceID,omitempty"`

	// TargetID is the unique identifier for the Target.
	TargetID string `json:"TargetID,omitempty"`

	// ToolchainType specifies the type of toolchain for this target.
	// required: true
	// example: "Kubernetes/YAML"
	ToolchainType string `json:"ToolchainType,omitempty"`

	// UpdatedAt is the timestamp when the entity was last updated in "2023-01-01T12:00:00Z" format.
	// Example: 2025-04-04T11:50:02.95102-07:00
	UpdatedAt string `json:"UpdatedAt,omitempty"`

	// Version is an entity-specific sequence number used for optimistic concurrency control.
	// The value read must be sent in calls to Update.
	Version int64 `json:"Version,omitempty"`
}

// Validate validates this models target
func (m *ModelsTarget) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models target based on context it is used
func (m *ModelsTarget) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsTarget) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsTarget) UnmarshalBinary(b []byte) error {
	var res ModelsTarget
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
