// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

// Code generated by go-swagger; DO NOT EDIT.
package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsExtendedTarget models extended target
//
// swagger:model models.ExtendedTarget
type ModelsExtendedTarget struct {

	// bridge worker
	BridgeWorker *ModelsBridgeWorker `json:"BridgeWorker,omitempty"`

	// organization
	Organization *ModelsOrganization `json:"Organization,omitempty"`

	// space
	Space *ModelsSpace `json:"Space,omitempty"`

	// target
	Target *ModelsTarget `json:"Target,omitempty"`
}

// Validate validates this models extended target
func (m *ModelsExtendedTarget) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBridgeWorker(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrganization(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSpace(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTarget(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsExtendedTarget) validateBridgeWorker(formats strfmt.Registry) error {
	if swag.IsZero(m.BridgeWorker) { // not required
		return nil
	}

	if m.BridgeWorker != nil {
		if err := m.BridgeWorker.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("BridgeWorker")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("BridgeWorker")
			}
			return err
		}
	}

	return nil
}

func (m *ModelsExtendedTarget) validateOrganization(formats strfmt.Registry) error {
	if swag.IsZero(m.Organization) { // not required
		return nil
	}

	if m.Organization != nil {
		if err := m.Organization.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Organization")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Organization")
			}
			return err
		}
	}

	return nil
}

func (m *ModelsExtendedTarget) validateSpace(formats strfmt.Registry) error {
	if swag.IsZero(m.Space) { // not required
		return nil
	}

	if m.Space != nil {
		if err := m.Space.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Space")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Space")
			}
			return err
		}
	}

	return nil
}

func (m *ModelsExtendedTarget) validateTarget(formats strfmt.Registry) error {
	if swag.IsZero(m.Target) { // not required
		return nil
	}

	if m.Target != nil {
		if err := m.Target.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Target")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Target")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this models extended target based on the context it is used
func (m *ModelsExtendedTarget) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBridgeWorker(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOrganization(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSpace(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTarget(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsExtendedTarget) contextValidateBridgeWorker(ctx context.Context, formats strfmt.Registry) error {

	if m.BridgeWorker != nil {

		if swag.IsZero(m.BridgeWorker) { // not required
			return nil
		}

		if err := m.BridgeWorker.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("BridgeWorker")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("BridgeWorker")
			}
			return err
		}
	}

	return nil
}

func (m *ModelsExtendedTarget) contextValidateOrganization(ctx context.Context, formats strfmt.Registry) error {

	if m.Organization != nil {

		if swag.IsZero(m.Organization) { // not required
			return nil
		}

		if err := m.Organization.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Organization")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Organization")
			}
			return err
		}
	}

	return nil
}

func (m *ModelsExtendedTarget) contextValidateSpace(ctx context.Context, formats strfmt.Registry) error {

	if m.Space != nil {

		if swag.IsZero(m.Space) { // not required
			return nil
		}

		if err := m.Space.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Space")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Space")
			}
			return err
		}
	}

	return nil
}

func (m *ModelsExtendedTarget) contextValidateTarget(ctx context.Context, formats strfmt.Registry) error {

	if m.Target != nil {

		if swag.IsZero(m.Target) { // not required
			return nil
		}

		if err := m.Target.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Target")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Target")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelsExtendedTarget) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsExtendedTarget) UnmarshalBinary(b []byte) error {
	var res ModelsExtendedTarget
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
