// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

// Code generated by go-swagger; DO NOT EDIT.
package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsUnitEvent models unit event
//
// swagger:model models.UnitEvent
type ModelsUnitEvent struct {

	// action
	Action string `json:"Action,omitempty"`

	// CreatedAt is the timestamp when the entity was created in "2023-01-01T12:00:00Z" format.
	// Example: 2025-04-04T11:50:02.95102-07:00
	CreatedAt string `json:"CreatedAt,omitempty"`

	// CursorID is an auto-incrementing sequence number used for pagination.
	CursorID int64 `json:"CursorID,omitempty"`

	// message
	Message string `json:"Message,omitempty"`

	// organization ID
	OrganizationID string `json:"OrganizationID,omitempty"`

	// QueuedOperationID links this event back to the specific operation that triggered it.
	QueuedOperationID string `json:"QueuedOperationID,omitempty"`

	// result
	Result string `json:"Result,omitempty"`

	// revision num
	RevisionNum int64 `json:"RevisionNum,omitempty"`

	// space ID
	SpaceID string `json:"SpaceID,omitempty"`

	// started at
	StartedAt string `json:"StartedAt,omitempty"`

	// status
	Status string `json:"Status,omitempty"`

	// terminated at
	TerminatedAt string `json:"TerminatedAt,omitempty"`

	// UnitEventID is the unique identifier for this unit event.
	UnitEventID string `json:"UnitEventID,omitempty"`

	// unit ID
	UnitID string `json:"UnitID,omitempty"`

	// UpdatedAt is the timestamp when the entity was last updated in "2023-01-01T12:00:00Z" format.
	// Example: 2025-04-04T11:50:02.95102-07:00
	UpdatedAt string `json:"UpdatedAt,omitempty"`

	// Version is an entity-specific sequence number used for optimistic concurrency control.
	// The value read must be sent in calls to Update.
	Version int64 `json:"Version,omitempty"`
}

// Validate validates this models unit event
func (m *ModelsUnitEvent) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models unit event based on context it is used
func (m *ModelsUnitEvent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsUnitEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsUnitEvent) UnmarshalBinary(b []byte) error {
	var res ModelsUnitEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
