// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

// Code generated by go-swagger; DO NOT EDIT.
package link

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLinkParams creates a new GetLinkParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetLinkParams() *GetLinkParams {
	return &GetLinkParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetLinkParamsWithTimeout creates a new GetLinkParams object
// with the ability to set a timeout on a request.
func NewGetLinkParamsWithTimeout(timeout time.Duration) *GetLinkParams {
	return &GetLinkParams{
		timeout: timeout,
	}
}

// NewGetLinkParamsWithContext creates a new GetLinkParams object
// with the ability to set a context for a request.
func NewGetLinkParamsWithContext(ctx context.Context) *GetLinkParams {
	return &GetLinkParams{
		Context: ctx,
	}
}

// NewGetLinkParamsWithHTTPClient creates a new GetLinkParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetLinkParamsWithHTTPClient(client *http.Client) *GetLinkParams {
	return &GetLinkParams{
		HTTPClient: client,
	}
}

/*
GetLinkParams contains all the parameters to send to the API endpoint

	for the get link operation.

	Typically these are written to a http.Request.
*/
type GetLinkParams struct {

	/* LinkID.

	   Link ID
	*/
	LinkID string

	/* SpaceID.

	   Space ID
	*/
	SpaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLinkParams) WithDefaults() *GetLinkParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLinkParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get link params
func (o *GetLinkParams) WithTimeout(timeout time.Duration) *GetLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get link params
func (o *GetLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get link params
func (o *GetLinkParams) WithContext(ctx context.Context) *GetLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get link params
func (o *GetLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get link params
func (o *GetLinkParams) WithHTTPClient(client *http.Client) *GetLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get link params
func (o *GetLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLinkID adds the linkID to the get link params
func (o *GetLinkParams) WithLinkID(linkID string) *GetLinkParams {
	o.SetLinkID(linkID)
	return o
}

// SetLinkID adds the linkId to the get link params
func (o *GetLinkParams) SetLinkID(linkID string) {
	o.LinkID = linkID
}

// WithSpaceID adds the spaceID to the get link params
func (o *GetLinkParams) WithSpaceID(spaceID string) *GetLinkParams {
	o.SetSpaceID(spaceID)
	return o
}

// SetSpaceID adds the spaceId to the get link params
func (o *GetLinkParams) SetSpaceID(spaceID string) {
	o.SpaceID = spaceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param link_id
	if err := r.SetPathParam("link_id", o.LinkID); err != nil {
		return err
	}

	// path param space_id
	if err := r.SetPathParam("space_id", o.SpaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
