app.features.0=authentication
app.features.1=logging
app.name=MyApplication
app.version=1.0.0
configHub.configName=MyApplicationConfig
configHub.configSchema=SimpleApp
# One comment
database.host=localhost
database.port=5432 # Two comment
database.ssl.enabled=true
