apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: replaceme
  name: replaceme
  namespace: replaceme
spec:
  replicas: 999999999
  paused: false
  selector:
    matchLabels:
      app: replaceme
  strategy: {}
  template:
    metadata:
      labels:
        app: replaceme
    spec:
      serviceAccountName: replaceme
      containers:
      - image: replaceme:latest
        name: main
        ports:
        - containerPort: 8080
        resources: {}
        env:
        - value: replaceme
          name: DATABASE_HOST
        - value: replaceme
          name: DATABASE_PORT
        - value: replaceme
          name: DATABASE_NAME
        - value: replaceme
          name: DATABASE_USER
        - value: replaceme
          name: DATABASE_PASSWORD
        envFrom:
        - configMapRef:
            name: replaceme
