// Copyright (C) ConfigHub, Inc.
// SPDX-License-Identifier: MIT

// Code generated by go-swagger; DO NOT EDIT.
package unit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUnitParams creates a new GetUnitParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUnitParams() *GetUnitParams {
	return &GetUnitParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUnitParamsWithTimeout creates a new GetUnitParams object
// with the ability to set a timeout on a request.
func NewGetUnitParamsWithTimeout(timeout time.Duration) *GetUnitParams {
	return &GetUnitParams{
		timeout: timeout,
	}
}

// NewGetUnitParamsWithContext creates a new GetUnitParams object
// with the ability to set a context for a request.
func NewGetUnitParamsWithContext(ctx context.Context) *GetUnitParams {
	return &GetUnitParams{
		Context: ctx,
	}
}

// NewGetUnitParamsWithHTTPClient creates a new GetUnitParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUnitParamsWithHTTPClient(client *http.Client) *GetUnitParams {
	return &GetUnitParams{
		HTTPClient: client,
	}
}

/*
GetUnitParams contains all the parameters to send to the API endpoint

	for the get unit operation.

	Typically these are written to a http.Request.
*/
type GetUnitParams struct {

	/* SpaceID.

	   Space ID
	*/
	SpaceID string

	/* UnitID.

	   Unit ID
	*/
	UnitID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get unit params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUnitParams) WithDefaults() *GetUnitParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get unit params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUnitParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get unit params
func (o *GetUnitParams) WithTimeout(timeout time.Duration) *GetUnitParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get unit params
func (o *GetUnitParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get unit params
func (o *GetUnitParams) WithContext(ctx context.Context) *GetUnitParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get unit params
func (o *GetUnitParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get unit params
func (o *GetUnitParams) WithHTTPClient(client *http.Client) *GetUnitParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get unit params
func (o *GetUnitParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSpaceID adds the spaceID to the get unit params
func (o *GetUnitParams) WithSpaceID(spaceID string) *GetUnitParams {
	o.SetSpaceID(spaceID)
	return o
}

// SetSpaceID adds the spaceId to the get unit params
func (o *GetUnitParams) SetSpaceID(spaceID string) {
	o.SpaceID = spaceID
}

// WithUnitID adds the unitID to the get unit params
func (o *GetUnitParams) WithUnitID(unitID string) *GetUnitParams {
	o.SetUnitID(unitID)
	return o
}

// SetUnitID adds the unitId to the get unit params
func (o *GetUnitParams) SetUnitID(unitID string) {
	o.UnitID = unitID
}

// WriteToRequest writes these params to a swagger request
func (o *GetUnitParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param space_id
	if err := r.SetPathParam("space_id", o.SpaceID); err != nil {
		return err
	}

	// path param unit_id
	if err := r.SetPathParam("unit_id", o.UnitID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
