# Document header comment
---
# Regular head comment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydep
  annotations:
    confighub.com/key: something
  name: mydep
  namespace: example
  # Foot comment
spec:
  replicas: 3 # Line comment on replicas
  paused: false
  selector:
    matchLabels:
      app: mydep
  strategy: {}
  # Line head comment
  template:
    metadata:
      labels:
        app: mydep
    spec:
      dnsPolicy: ClusterFirst
      containers:
      # Array comment
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 8080
        resources: {}
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 30
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
      # Internal array comment
      - image: otel/opentelemetry-collector:latest-amd64
        name: otel-sidecar
        ports: # Middle line comment
        - containerPort: 4318
        startupProbe:
          httpGet:
            path: /healthz
            port: 4318
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 30
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4318
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 4318
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
